# Generated by Django 6.0.7 on 2026-07-19 18:51
# Manually updated: backfill slugs before applying unique constraint.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def backfill_slugs(apps, schema_editor):
    """
    Generates a unique slug for every existing Blog row that has no slug.
    Runs before the unique constraint is enforced so the migration succeeds
    on databases that already contain data.
    """
    Blog = apps.get_model('blog', 'Blog')
    for post in Blog.objects.filter(slug=''):
        base_slug = slugify(post.title) or f'post-{post.pk}'
        slug = base_slug
        counter = 1
        # Ensure uniqueness among siblings being processed
        while Blog.objects.filter(slug=slug).exclude(pk=post.pk).exists():
            slug = f'{base_slug}-{counter}'
            counter += 1
        post.slug = slug
        post.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_number_of_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
            },
        ),
        migrations.RemoveField(
            model_name='blog',
            name='isPublished',
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='blog_posts',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/featured_images/'),
        ),
        # Step 1: Add slug as non-unique so existing rows get an empty string default
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, default=''),
            preserve_default=False,
        ),
        # Step 2: Fill in slugs for existing rows before enforcing uniqueness
        migrations.RunPython(backfill_slugs, migrations.RunPython.noop),
        # Step 3: Now safe to add the unique constraint
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(
                choices=[('draft', 'Draft'), ('published', 'Published')],
                default='draft',
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name='blog',
            name='number_of_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['-created_at'], name='blog_blog_created_602a4f_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['status'], name='blog_blog_status_e6780b_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['slug'], name='blog_blog_slug_d925e3_idx'),
        ),
    ]
